# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: IPFire Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-09-29 14:20+0000\n"
"PO-Revision-Date: 2014-10-31 14:54+0000\n"
"Last-Translator: Blago Culjak <blago.culjak@hotmail.com>\n"
"Language-Team: Croatian (http://www.transifex.com/mstremer/ipfire/language/hr/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: hr\n"
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"

#: ../src/ddns/__init__.py:63
msgid "Debugging mode enabled"
msgstr "Debugging mod je omogućen"

#: ../src/ddns/__init__.py:90
#, python-format
msgid "Loading configuration file %s"
msgstr "Otvaram konfiguracijsku datoteku %s"

#: ../src/ddns/__init__.py:156
msgid "Found no entries in the configuration file. Exiting."
msgstr "Nisu pronađeni unosi u konfiguracijskoj datoteci. Izlaz."

#: ../src/ddns/__init__.py:167
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) failed:"
msgstr "Dinamičko DNS ažuriranje za %(hostname)s (%(provider)s) nije uspjelo:"

#: ../src/ddns/__init__.py:174
#, python-format
msgid ""
"Dynamic DNS update for %(hostname)s (%(provider)s) throwed an unhandled "
"exception:"
msgstr "Dinamičko DNS ažuriranje za  %(hostname)s (%(provider)s) vratilo je neočekivan izuzetak:"

#: ../src/ddns/errors.py:29
msgid "Error"
msgstr "Pogreška"

#: ../src/ddns/errors.py:39
msgid "Network error"
msgstr "Pogreška mreže"

#: ../src/ddns/errors.py:47
msgid ""
"The server denied processing the request because account abuse is suspected"
msgstr "Poslužitelj je odbio obradu zahtjeva, jer sumnja na zloupotrebu računa"

#: ../src/ddns/errors.py:55
msgid "Authentication against the server has failed"
msgstr "Autentifikacija na poslužitelju nije uspjela"

#: ../src/ddns/errors.py:64
msgid "The server denies any updates from this client"
msgstr "Poslužitelj odbija bilo kakva ažuriranja ovog klijenta"

#: ../src/ddns/errors.py:72
msgid "The configuration file has errors"
msgstr "Konfiguracija datoteka sadrži pogreške"

#: ../src/ddns/errors.py:79
msgid "Connection refused"
msgstr "Veza odbijena"

#: ../src/ddns/errors.py:86 ../src/ddns/system.py:218
msgid "Connection timeout"
msgstr "Timeout (istek vremena) veze"

#: ../src/ddns/errors.py:94
msgid "The host could not be found in the configuration file"
msgstr "Domaćin (host) nije pronađen u datoteci"

#: ../src/ddns/errors.py:102
msgid "Internal server error"
msgstr "Interna pogreška poslužitelja"

#: ../src/ddns/errors.py:109
msgid "Network unreachable"
msgstr "Mreža je nedostupna"

#: ../src/ddns/errors.py:116
msgid "Not found"
msgstr "Nije pronađeno"

#: ../src/ddns/errors.py:124
msgid "Request error"
msgstr "Zahtjev pogreške"

#: ../src/ddns/errors.py:132
msgid "Could not resolve DNS entry"
msgstr "Nije moguće razriješiti DNS unos"

#: ../src/ddns/errors.py:139
msgid "Service unavailable"
msgstr "Usluga nije dostupna"

#: ../src/ddns/errors.py:147
msgid "The update could not be performed"
msgstr "Ažuriranje nije moglo biti provedeno"

#: ../src/ddns/providers.py:85
msgid "Provider is not properly configured"
msgstr "Provider nije ispravno konfiguriran"

#: ../src/ddns/providers.py:154
#, python-format
msgid "Updating %s forced"
msgstr "Prisilno ažuriranje %s"

#: ../src/ddns/providers.py:170
#, python-format
msgid "Dynamic DNS update for %(hostname)s (%(provider)s) successful"
msgstr "Dinamičko DNS ažuriranje za %(hostname)s (%(provider)s) uspješno"

#: ../src/ddns/providers.py:194
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because of an IP "
"address change"
msgstr "Ažuriranje za %(hostname)s (%(provider)s) se provodi zbog promjene IP adrese"

#: ../src/ddns/providers.py:202
#, python-format
msgid ""
"An update for %(hostname)s (%(provider)s) is performed because the holdoff "
"time has expired"
msgstr "Ažuriranje za %(hostname)s (%(provider)s) se provodi, jer holdoff vrijeme je isteklo"

#. Otherwise, we don't need to perform an update
#: ../src/ddns/providers.py:209
#, python-format
msgid "No update required for %(hostname)s (%(provider)s)"
msgstr "Nije potrebno ažuriranje  za %(hostname)s (%(provider)s)"

#: ../src/ddns/providers.py:228 ../src/ddns/providers.py:242
#, python-format
msgid "An update has not been performed because earlier updates failed for %s"
msgstr "Ažuriranje nije provedeno, jer ranije ažuriranje za %s nije uspilo"

#: ../src/ddns/providers.py:230
msgid "There will be no retries"
msgstr "Neće biti više ponovnih pokušaja"

#: ../src/ddns/providers.py:246
msgid "Last failure message:"
msgstr "Posljednja poruka o grešci:"

#: ../src/ddns/providers.py:251
#, python-format
msgid "Further updates will be withheld until %s"
msgstr "Daljnje nadogradnje će biti zadržan do %s"

#: ../src/ddns/providers.py:385 ../src/ddns/providers.py:612
#: ../src/ddns/providers.py:1191 ../src/ddns/providers.py:1340
msgid "No valid FQDN was given."
msgstr "FQDN nije zadan."

#: ../src/ddns/providers.py:387
msgid "Specified host does not exist."
msgstr "Navedeni domaćin ne postoji."

#: ../src/ddns/providers.py:391
msgid "DNS error encountered."
msgstr "DNS pogreška."

#. If we got here, some other update error happened.
#: ../src/ddns/providers.py:396 ../src/ddns/providers.py:785
#, python-format
msgid "Server response: %s"
msgstr "Odgovor poslužitelja: %s"

#: ../src/ddns/providers.py:531
msgid "Scriptlet:"
msgstr "Scriptlet:"

#: ../src/ddns/providers.py:614 ../src/ddns/providers.py:661
msgid "Invalid hostname specified."
msgstr "Nevažeći navedeni poslužitelj."

#: ../src/ddns/providers.py:616
msgid "Hostname not marked as a dynamic host."
msgstr "Hostname nije označen kao dinamičan host (domaćin)."

#: ../src/ddns/providers.py:618 ../src/ddns/providers.py:670
#: ../src/ddns/providers.py:905
msgid "Invalid IP address has been sent."
msgstr "Poslana pogrešna IP adresa."

#: ../src/ddns/providers.py:658
msgid "No hostname specified."
msgstr "Nije naveden poslužitelj."

#: ../src/ddns/providers.py:667
msgid "Account has been disabled."
msgstr "Račun je onemogućen."

#: ../src/ddns/providers.py:673
msgid "Too many failed requests."
msgstr "Previše neuspjelih zahtjeva."

#: ../src/ddns/providers.py:776
msgid "Malformed request has been sent."
msgstr "Poslan je neispravan zahtjev."

#: ../src/ddns/providers.py:780
msgid "Too frequent update requests have been sent."
msgstr "Prečesto se zahtjevanja ažuriranje."

#: ../src/ddns/providers.py:826 ../src/ddns/providers.py:1013
msgid "Domain not found."
msgstr "Domena nije pronađena."

#: ../src/ddns/providers.py:861
msgid "An invalid IP address was submitted"
msgstr "Nepravilna IP adresa je predana"

#: ../src/ddns/providers.py:1015
msgid "Domain not active."
msgstr "Domena nije aktivna."

#: ../src/ddns/providers.py:1165
msgid "No Auth details specified."
msgstr "Nema navedenih autentifikacijskih detalja."

#: ../src/ddns/providers.py:1187
msgid "Invalid IPv4 address has been sent."
msgstr "Poslana pogrešna IPv4 adresa."

#: ../src/ddns/providers.py:1189
msgid "Invalid IPv6 address has been sent."
msgstr "Poslana pogrešna IPv6 adresa."

#: ../src/ddns/providers.py:1385
msgid "Invalid hostname specified"
msgstr "Nevažeći navedeni poslužitelj"

#: ../src/ddns/system.py:55
#, python-format
msgid "Running on distribution: %s"
msgstr "Radi na distribuciji: %s"

#: ../src/ddns/system.py:153
msgid "Request header:"
msgstr "Odgovor zaglavlja:"

#. Log response header.
#: ../src/ddns/system.py:161 ../src/ddns/system.py:170
#, python-format
msgid "Response header (Status Code %s):"
msgstr "Odgovor zaglavlja (kod statusa %s):"
